export const jwtConstants = {
  secret: process.env.TOKEN || 'TOKEN_DEV',
};

export const allResources = [
  'canCreate_modules',
  'canCreate_roles',
  'canCreate_users',
  'canEdit_modules',
  'canEdit_roles',
  'canEdit_users',
  'canDelete_modules',
  'canDelete_roles',
  'canDelete_users',
  'canPrint_roles',
  'canRead_modules',
  'canRead_roles',
  'canRead_users',
  'canChangePassword_users',
  'canRestore_users',
  'canRestore_modules',
  'canRestore_roles',
  'canRead_Resource',
  'canCreate_Resource',
  'canEdit_Resource',
  'canRead_ResourceR',
  'canCreate_ResourceR',
  'canEdit_ResourceR',
  'canReadRoleX_Resource',
  'canRead_menus',
  'canCreate_menus',
  'canEdit_menus',
  'canDelete_menus',
  'canRestore_menus',
];
